#if !canImport(ObjectiveC)
import XCTest

extension XCTObserverFailureReporterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCTObserverFailureReporterTests = [
        ("test", test),
    ]
}

extension XCTestFailureReporterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCTestFailureReporterTests = [
        ("test", test),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XCTObserverFailureReporterTests.__allTests__XCTObserverFailureReporterTests),
        testCase(XCTestFailureReporterTests.__allTests__XCTestFailureReporterTests),
    ]
}
#endif
